# 필요한 라이브러리 설치

In [1]:
# 필요한 라이브러리 설치
import copy
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
import warnings
warnings.filterwarnings('ignore')

# 데이터 불러오기

In [2]:
# 파일 받아오기
df1 =pd.read_csv("1year.csv")
df2 =pd.read_csv("2year.csv")
df3 =pd.read_csv("3year.csv")
df4 =pd.read_csv("4year.csv")
df5 =pd.read_csv("5year.csv")

# ID 제거

In [3]:
#ID 열은 제거
df1 = df1.drop(['id'], axis=1)
df2 = df2.drop(['id'], axis=1)
df3 = df3.drop(['id'], axis=1)
df4 = df4.drop(['id'], axis=1)
df5 = df5.drop(['id'], axis=1)
df_list = [df1, df2, df3, df4, df5]

# 중복 데이터 확인 및 제거

In [4]:
for i in range(5):
    if df_list[i].duplicated().sum()>0:
        # 중복제거
        print(df_list[i]," : 중복 데이터 Check!")
        print(df_list[i]," : 중복된 데이터 수 : ",df_list[i].duplicated().sum())
        df_list[i].drop_duplicates(subset=None, keep='first', inplace=True, ignore_index=True)
        print("제거 후 :" ,df_list[i].duplicated().sum())

         attr1    attr2    attr3    attr4     attr5     attr6     attr7  \
0     0.200550  0.37951  0.39641  2.04720   32.3510  0.388250  0.249760   
1     0.209120  0.49988  0.47225  1.94470   14.7860  0.000000  0.258340   
2     0.248660  0.69592  0.26713  1.55480   -1.1523  0.000000  0.309060   
3     0.081483  0.30734  0.45879  2.49280   51.9520  0.149880  0.092704   
4     0.187320  0.61323  0.22960  1.40630   -7.3128  0.187320  0.187320   
...        ...      ...      ...      ...       ...       ...       ...   
7022  0.018371  0.47410 -0.13619  0.60839  -18.4490  0.018371  0.018371   
7023 -0.013359  0.58354 -0.02265  0.92896  -42.2320 -0.013359 -0.015036   
7024  0.006338  0.50276  0.43923  1.87360    9.7417  0.006338  0.012022   
7025 -0.041643  0.84810 -0.12852  0.57485 -121.9200  0.000000 -0.036795   
7026  0.014946  0.94648  0.03211  1.03630  -20.5810  0.000000  0.015260   

         attr8    attr9    attr10  ...    attr56    attr57   attr58    attr59  \
0     1.330500  1.

          attr1    attr2     attr3    attr4     attr5     attr6     attr7  \
0      0.174190  0.41299  0.143710  1.34800  -28.9820  0.603830  0.219460   
1      0.146240  0.46038  0.282300  1.62940    2.5952  0.000000  0.171850   
2      0.000595  0.22612  0.488390  3.15990   84.8740  0.191140  0.004572   
3      0.024526  0.43236  0.275460  1.78330  -10.1050  0.569440  0.024526   
4      0.188290  0.41504  0.342310  1.92790  -58.2740  0.000000  0.233580   
...         ...      ...       ...      ...       ...       ...       ...   
10498  0.002861  0.58067 -0.223860  0.51658  -31.8660  0.002861  0.002861   
10499 -0.051968  0.55254  0.147150  2.16980   12.7480 -0.051968 -0.034361   
10500 -0.135900  0.83954 -0.342010  0.46526 -145.3100 -0.219120 -0.131860   
10501  0.009423  0.50028  0.261630  1.52300  -10.1580  0.009423  0.007700   
10502 -0.001775  0.94780  0.003729  1.00450  -50.2210  0.000000  0.002565   

          attr8    attr9    attr10  ...    attr56    attr57   attr58  \
0  

         attr1    attr2     attr3    attr4     attr5     attr6     attr7  \
0     0.088238  0.55472  0.011340  1.02050  -66.5200  0.342040  0.109490   
1    -0.006202  0.48465  0.232980  1.59980    6.1825  0.000000 -0.006202   
2     0.130240  0.22142  0.577510  3.60820  120.0400  0.187640  0.162120   
3    -0.089951  0.88700  0.269270  1.52220  -55.9920 -0.073957 -0.089951   
4     0.048179  0.55041  0.107650  1.24370  -22.9590  0.000000  0.059280   
...        ...      ...       ...      ...       ...       ...       ...   
5905  0.012898  0.70621  0.038857  1.17220  -18.9070  0.000000  0.013981   
5906 -0.578050  0.96702 -0.800850  0.16576  -67.3650 -0.578050 -0.578050   
5907 -0.179050  1.25530 -0.275990  0.74554 -120.4400 -0.179050 -0.154930   
5908 -0.108860  0.74394  0.015449  1.08780  -17.0030 -0.108860 -0.109180   
5909 -0.105370  0.53629 -0.045578  0.91478  -56.0680 -0.105370 -0.109940   

        attr8    attr9    attr10  ...    attr56    attr57   attr58    attr59  \
0     0

# 데이터 라벨링

In [5]:
df1 = df1.replace({'bankruptcy':1},{'bankruptcy':5})
df1 = df1.replace({'bankruptcy':0},{'bankruptcy':-5})

df2 = df2.replace({'bankruptcy':1},{'bankruptcy':4})
df2 = df2.replace({'bankruptcy':0},{'bankruptcy':-4})

df3 = df3.replace({'bankruptcy':1},{'bankruptcy':3})
df3 = df3.replace({'bankruptcy':0},{'bankruptcy':-3})

df4 = df4.replace({'bankruptcy':1},{'bankruptcy':2})
df4 = df4.replace({'bankruptcy':0},{'bankruptcy':-2})

df5 = df5.replace({'bankruptcy':1},{'bankruptcy':1})
df5 = df5.replace({'bankruptcy':0},{'bankruptcy':-1})

# 데이터 합치기

In [6]:
df = pd.concat([df1, df2, df3, df4, df5])

# SCALING

In [7]:
# unseen도 
#스케일링 전처리 , feature 값과 Y값 분리 
df_dataset = df.drop(labels=['bankruptcy'], axis=1)
df_y = pd.DataFrame(df['bankruptcy'])
df_y.reset_index(inplace=True)
df_y.drop(['index'], axis=1, inplace=True)
col_names = df_dataset.columns

from sklearn.preprocessing import StandardScaler
scaler_std = StandardScaler()
df_standard = scaler_std.fit_transform(df_dataset)
df_dataset = pd.DataFrame(df_standard, columns=col_names)

df = pd.concat([df_dataset, df_y], axis=1)

# X , Y 나누기
df_dataset = df.drop(labels=['bankruptcy'], axis=1)
df_y = pd.DataFrame(df['bankruptcy'])

# 1. Iterative 결측치 대체 방법

In [8]:
# Iterative Imputer를 이용한 다중대치
dummy = pd.get_dummies(df_dataset)
Mdf_dataset = pd.DataFrame(IterativeImputer(verbose=False).fit_transform(dummy)
                           ,columns = df_dataset.columns)
Mdf = pd.concat([Mdf_dataset, df_y], axis=1)

# 2. 단순 대치법( 열과 행 )

In [9]:
# 상위 5개 지워
Sdf = df.drop(['attr37', 'attr27', 'attr60', 'attr45', 'attr21'], axis=1)
# 결측치 존재하는 rows에 대해서는 단순 대치
Sdf = Sdf.dropna(axis=0)

# 3. KNN 결측치 대체 방법

In [10]:
imputer=KNNImputer(n_neighbors=5)

Kdf_dataset = imputer.fit_transform(df_dataset)
Kdf_dataset = pd.DataFrame(Kdf_dataset, columns = df_dataset.columns)
Kdf = pd.concat([Kdf_dataset, df_y], axis=1)

# 데이터 라벨링 1-> 1, 0 ->-1

# Unseen Data 추출

In [11]:
Kdf1 = copy.deepcopy(Kdf)
Mdf1 = copy.deepcopy(Mdf)
Sdf1 = copy.deepcopy(Sdf)
def extrating_unseen(df):
    print(df['bankruptcy'].unique())
    label_nb = [-5,-4,-3,-2,-1]
    unseen = pd.DataFrame
    for i in label_nb:
        unseen_data = df[df['bankruptcy']==i].sample(n=2)
        for j in range(2):
            df = df.drop([unseen_data.index[j],], axis = 0) 
            if(unseen.empty):
                unseen = unseen_data
            else:
                unseen = pd.concat([unseen, unseen_data]) 
            
    label_b = [1,2,3,4,5]
    for i in label_b:
        unseen_data = df[df['bankruptcy']==i].sample(n=10)
        for j in range(10):
            df = df.drop([unseen_data.index[j],], axis = 0)
            unseen = pd.concat([unseen, unseen_data]) 
#     df.reset_index(inplace=True)
#     unseen.reset_index(inplace=True)
#     df = df.drop(['index'], axis = 1)
#     unseen = unseen.drop(['index'], axis = 1)
    return df, unseen

Kdf1, Kunseen = extrating_unseen(Kdf)
Mdf1, Munseen = extrating_unseen(Mdf)
Sdf1, Sunseen = extrating_unseen(Sdf)

[-5  5 -4  4 -3  3 -2  2 -1  1]
[-5  5 -4  4 -3  3 -2  2 -1  1]
[-5  5 -4  4 -3  3 -2  2 -1  1]


In [12]:
Kunseen

attr1     attr2     attr3     attr4     attr5     attr6     attr7  \
5747  0.010296 -0.038406 -0.011084 -0.017323  0.005132  0.004533 -0.001298   
76    0.069792  0.023215  0.015726 -0.017015  0.006190  0.007962  0.033755   
5747  0.010296 -0.038406 -0.011084 -0.017323  0.005132  0.004533 -0.001298   
76    0.069792  0.023215  0.015726 -0.017015  0.006190  0.007962  0.033755   
8994 -0.072430  0.015833 -0.085528 -0.019820  0.000136 -0.030092 -0.045125   
...        ...       ...       ...       ...       ...       ...       ...   
6752  0.038565 -0.072271 -0.002816 -0.016031  0.006660  0.028209  0.008786   
6911  0.000080 -0.038922 -0.006109 -0.017262  0.005619  0.013629 -0.008127   
6687  0.001446  0.038211  0.040699 -0.016300  0.004826  0.005378  0.003636   
6779  0.112767  0.002988 -0.048221 -0.019075  0.005643  0.056321  0.044459   
6928  0.035504  0.467450 -0.453403 -0.020394  0.004842 -0.461484  0.007084   

         attr8     attr9    attr10  ...    attr56    attr57    attr58  \
5747 -0.021121 -0.031501  0.002056  ...  0.004985  0.008657 -0.005513   
76   -0.023901  0.013527 -0.023835  ...  0.004961  0.062878 -0.005483   
5747 -0.021121 -0.031501  0.002056  ...  0.004985  0.008657 -0.005513   
76   -0.023901  0.013527 -0.023835  ...  0.004961  0.062878 -0.005483   
8994 -0.023723 -0.035734 -0.020733  ...  0.004886 -0.035708 -0.005392   
...        ...       ...       ...  ...       ...       ...       ...   
6752 -0.014505 -0.021934  0.016179  ...  0.004982  0.013563 -0.005504   
6911 -0.021257 -0.025716 -0.000044  ...  0.004948  0.005669 -0.005471   
6687 -0.024205 -0.001827 -0.030134  ...  0.004952  0.018448 -0.005483   
6779 -0.023352 -0.022217 -0.015337  ...  0.004980  0.065941 -0.005502   
6928 -0.026102  0.122684 -0.210465  ...  0.004946 -0.003576 -0.005471   

        attr59    attr60    attr61    attr62    attr63    attr64  bankruptcy  
5747 -0.010403 -0.013778 -0.020659 -0.009771 -0.054528 -0.030138          -5  
76   -0.010907 -0.013490 -0.016255 -0.010265 -0.035045 -0.018810          -5  
5747 -0.010403 -0.013778 -0.020659 -0.009771 -0.054528 -0.030138          -5  
76   -0.010907 -0.013490 -0.016255 -0.010265 -0.035045 -0.018810          -5  
8994 -0.010641 -0.013837 -0.024338 -0.006674 -0.070011 -0.030299          -4  
...        ...       ...       ...       ...       ...       ...         ...  
6752 -0.010907 -0.011860 -0.021059 -0.010182 -0.040572 -0.030137           5  
6911 -0.010907 -0.013687  0.030301 -0.010433 -0.016162 -0.028531           5  
6687 -0.010907 -0.013806  0.118700 -0.010085 -0.045338  0.014046           5  
6779 -0.008047  0.003137 -0.018890 -0.010132 -0.043202 -0.029384           5  
6928 -0.010907 -0.006779 -0.008033 -0.009916 -0.051097  0.117390           5  

[520 rows x 65 columns]

# Each 학습 DF 와 Unseen 생성

In [13]:
Kdf_names = ['Kdf_5year.csv','Kdf_4year.csv','Kdf_3year.csv','Kdf_2year.csv','Kdf_1year.csv']
Mdf_names = ['Mdf_5year.csv','Mdf_4year.csv','Mdf_3year.csv','Mdf_2year.csv','Mdf_1year.csv']
Sdf_names = ['Sdf_5year.csv','Sdf_4year.csv','Sdf_3year.csv','Sdf_2year.csv','Sdf_1year.csv']
def extrating_df(df, names):
    df_list = []
    for i in range(1,6):
        df_nb = df[df['bankruptcy']== -i]
        df_b = df[df['bankruptcy']== i]
        df_sum = pd.concat([df_nb, df_b])
        df_list.append(df_sum)
    for i in range(5):
        df_list[i].to_csv(names[i],index=False)    


extrating_df(Kdf1, Kdf_names)
extrating_df(Mdf1, Mdf_names)
extrating_df(Sdf1, Sdf_names)

Kunseen.to_csv('Kdf_unseen_10label.csv',index=False)
Munseen.to_csv('Mdf_unseen_10label.csv',index=False)
Sunseen.to_csv('Sdf_unseen_10label.csv',index=False)

Kdf1.to_csv('Kdf_10label.csv',index=False)
Mdf1.to_csv('Mdf_10label.csv',index=False)
Sdf1.to_csv('Sdf_10label.csv',index=False)

In [14]:
def relabeling(df):
    df = df.replace({'bankruptcy':-5},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-4},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-3},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-2},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-1},{'bankruptcy':0})
    return df

Kdf_re = relabeling(Kdf1)
Mdf_re = relabeling(Mdf1)
Sdf_re = relabeling(Sdf1)
dfre_list = [Kdf_re,Mdf_re,Sdf_re]

Kunseen_re = relabeling(Kunseen)
Munseen_re = relabeling(Munseen)
Sunseen_re = relabeling(Sunseen)
unseenre_list = [Kunseen_re,Munseen_re,Sunseen_re]

dfre_names = ['Kdf_6label.csv','Mdf_6label.csv','Sdf_6label.csv']
unseenre_names = ['Kdf_unseen_6label.csv','Mdf_unseen_6label.csv','Sdf_unseen_6label.csv']
def tocsv(relist, names):
    for i in range(3):
        relist[i].to_csv(names[i],index=False) 
        
tocsv(dfre_list, dfre_names)
tocsv(unseenre_list,unseenre_names)

In [15]:
def relabeling(df):
    df = df.replace({'bankruptcy':-5},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-4},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-3},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-2},{'bankruptcy':0})
    df = df.replace({'bankruptcy':-1},{'bankruptcy':0})
    df = df.replace({'bankruptcy':1},{'bankruptcy':1})
    df = df.replace({'bankruptcy':2},{'bankruptcy':1})
    df = df.replace({'bankruptcy':3},{'bankruptcy':2})
    df = df.replace({'bankruptcy':4},{'bankruptcy':2})
    df = df.replace({'bankruptcy':5},{'bankruptcy':0})
    return df

Kdf_re = relabeling(Kdf1)
Mdf_re = relabeling(Mdf1)
Sdf_re = relabeling(Sdf1)
dfre_list = [Kdf_re,Mdf_re,Sdf_re]

Kunseen_re = relabeling(Kunseen)
Munseen_re = relabeling(Munseen)
Sunseen_re = relabeling(Sunseen)
unseenre_list = [Kunseen_re,Munseen_re,Sunseen_re]

dfre_names = ['Kdf_3label.csv','Mdf_3label.csv','Sdf_3label.csv']
unseenre_names = ['Kdf_unseen_3label.csv','Mdf_unseen_3label.csv','Sdf_unseen_3label.csv']
def tocsv(relist, names):
    for i in range(3):
        relist[i].to_csv(names[i],index=False) 
        
tocsv(dfre_list, dfre_names)
tocsv(unseenre_list,unseenre_names)

In [16]:
print(Kdf_re['bankruptcy'].unique())

[0 2 1]
